import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bdoGrotesk = localFont({
  src: "../../public/BDOGrotesk-VF-BF648a657078401.ttf",
  variable: "--font-bdo-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bdoGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
